data = {
    "Afghanistan" : {"capital" : {"Kabul"}, "regions": ["asia"]},
    "Albania" : {"capital" : {"Tirana"}, "regions": ["europe"]},
    "Algeria" : {"capital" : {"Algiers"}, "regions": ["africa"]},
    "Andorra" : {"capital" : {"Andorra la Vella"}, "regions": ["europe"]},
    "Angola" : {"capital" : {"Luanda"}, "regions": ["africa"]},
    "Antigua and Barbuda" : {"capital" : {"St. John's"}, "regions": ["north_america", "americas", "caribbean"]},
    "Argentina" : {"capital" : {"Buenos Aires"}, "regions": ["south_america", "americas"]},
    "Armenia" : {"capital" : {"Yerevan"}, "regions": ["asia"]},
    "Australia" : {"capital" : {"Canberra"}, "regions": ["oceania"]},
    "Austria" : {"capital" : {"Vienna"}, "regions": ["europe"]},
    "Azerbaijan" : {"capital" : {"Baku"}, "regions": ["asia", "europe"]},
    "Bahamas" : {"capital" : {"Nassau"}, "regions": ["north_america", "americas", "caribbean"]},
    "Bahrain" : {"capital" : {"Manama"}, "regions": ["asia", "middle_east"]},
    "Bangladesh" : {"capital" : {"Dhaka"}, "regions": ["asia"]},
    "Barbados" : {"capital" : {"Bridgetown"}, "regions": ["north_america", "americas", "caribbean"]},
    "Belarus" : {"capital" : {"Minsk"}, "regions": ["europe"]},
    "Belgium" : {"capital" : {"Brussels"}, "regions": ["europe"]},
    "Belize" : {"capital" : {"Belmopan"}, "regions": ["north_america", "central_america", "americas"]},
    "Benin" : {"capital" : {"Porto Novo"}, "regions": ["africa"]},
    "Bhutan" : {"capital" : {"Thimphu"}, "regions": ["asia"]},
    "Bolivia" : {"capital" : {"La Paz", "Sucre"}, "regions": ["south_america", "americas"]},
    "Bosnia and Herzegovina" : {"capital" : {"Sarajevo"}, "regions": ["europe"]},
    "Botswana" : {"capital" : {"Gaborone"}, "regions": ["africa"]},
    "Brazil" : {"capital" : {"Brasília"}, "regions": ["south_america", "americas"]},
    "Brunei" : {"capital" : {"Bandar Seri Begawan"}, "regions": ["asia", "southeast_asia"]},
    "Bulgaria" : {"capital" : {"Sofia"}, "regions": ["europe"]},
    "Burkina Faso" : {"capital" : {"Ouagadougou"}, "regions": ["africa"]},
    "Burundi" : {"capital" : {"Bujumbura"}, "regions": ["africa"]},
    "Cambodia" : {"capital" : {"Phnom Penh"}, "regions": ["asia", "southeast_asia"]},
    "Cameroon" : {"capital" : {"Yaoundé"}, "regions": ["africa"]},
    "Canada" : {"capital" : {"Ottawa"}, "regions": ["north_america", "americas"]},
    "Cape Verde" : {"capital" : {"Praia"}, "regions": ["africa"]},
    "Cayman Islands" : {"capital" : {"George Town"}, "sovereign": False, "regions": ["north_america", "americas", "caribbean"]},
    "Central African Republic" : {"capital" : {"Bangui"}, "regions": ["africa"]},
    "Chad" : {"capital" : {"N'Djamena"}, "regions": ["africa"]},
    "Chile" : {"capital" : {"Santiago"}, "regions": ["south_america", "americas"]},
    "China" : {"capital" : {"Beijing"}, "regions": ["asia"]},
    "Colombia" : {"capital" : {"Bogotá"}, "regions": ["south_america", "americas"]},
    "Comoros" : {"capital" : {"Moroni"}, "regions": ["africa"]},
    "Cook Islands" : {"capital" : {"Avarua"}, "sovereign": False, "regions": ["oceania"]},
    "Costa Rica" : {"capital" : {"San José"}, "regions": ["north_america", "central_america", "americas"]},
    "Côte d'Ivoire" : {"capital" : {"Yamoussoukro"}, "regions": ["africa"]},
    "Croatia" : {"capital" : {"Zagreb"}, "regions": ["europe"]},
    "Cuba" : {"capital" : {"Havana"}, "regions": ["north_america", "americas", "caribbean"]},
    "Cyprus" : {"capital" : {"Nicosia"}, "regions": ["europe"]},
    "Czech Republic" : {"capital" : {"Prague"}, "regions": ["europe"]},
    "Democratic Republic of the Congo" : {"capital" : {"Kinshasa"}, "regions": ["africa"]},
    "Denmark" : {"capital" : {"Copenhagen"}, "regions": ["europe"]},
    "Djibouti" : {"capital" : {"Djibouti"}, "regions": ["africa"]},
    "Dominica" : {"capital" : {"Roseau"}, "regions": ["north_america", "americas", "caribbean"]},
    "Dominican Republic" : {"capital" : {"Santo Domingo"}, "regions": ["north_america", "americas", "caribbean"]},
    "East Timor" : {"capital" : {"Dili"}, "regions": ["asia", "southeast_asia"]},
    "Ecuador" : {"capital" : {"Quito"}, "regions": ["south_america", "americas"]},
    "Egypt" : {"capital" : {"Cairo"}, "regions": ["africa", "asia", "middle_east"]},
    "El Salvador" : {"capital" : {"San Salvador"}, "regions": ["north_america", "central_america", "americas"]},
    "Equatorial Guinea" : {"capital" : {"Malabo"}, "regions": ["africa"]},
    "Eritrea" : {"capital" : {"Asmara"}, "regions": ["africa"]},
    "Estonia" : {"capital" : {"Tallinn"}, "regions": ["europe"]},
    "Eswatini" : {"capital" : {"Mbabane"}, "regions": ["africa"]},
    "Ethiopia" : {"capital" : {"Addis Ababa"}, "regions": ["africa"]},
    "Faroe Islands" : {"capital": {"Tórshavn"}, "sovereign": False, "regions": ["europe"]},
    "Fiji" : {"capital" : {"Suva"}, "regions": ["oceania"]},
    "Finland" : {"capital" : {"Helsinki"}, "regions": ["europe"]},
    "France" : {"capital" : {"Paris"}, "regions": ["europe"]},
    "French Guiana" : {"capital" : {"Cayenne"}, "sovereign": False, "regions": ["south_america", "americas"]},
    "Gabon" : {"capital" : {"Libreville"}, "regions": ["africa"]},
    "Gambia" : {"capital" : {"Banjul"}, "regions": ["africa"]},
    "Georgia" : {"capital" : {"Tbilisi"}, "regions": ["asia", "europe"]},
    "Germany" : {"capital" : {"Berlin"}, "regions": ["europe"]},
    "Ghana" : {"capital" : {"Accra"}, "regions": ["africa"]},
    "Greece" : {"capital" : {"Athens"}, "regions": ["europe"]},
    "Greenland" : {"capital": {"Nuuk"}, "sovereign": False, "regions": ["europe"]},
    "Grenada" : {"capital" : {"St. George's"}, "regions": ["north_america", "americas", "caribbean"]},
    "Guatemala" : {"capital" : {"Guatemala City"}, "regions": ["north_america", "central_america", "americas"]},
    "Guinea" : {"capital" : {"Conakry"}, "regions": ["africa"]},
    "Guinea-Bissau" : {"capital" : {"Bissau"}, "regions": ["africa"]},
    "Guyana" : {"capital" : {"Georgetown"}, "regions": ["south_america", "americas"]},
    "Haiti" : {"capital" : {"Port-au-Prince"}, "regions": ["north_america", "americas", "caribbean"]},
    "Honduras" : {"capital" : {"Tegucigalpa"}, "regions": ["north_america", "central_america", "americas"]},
    "Hungary" : {"capital" : {"Budapest"}, "regions": ["europe"]},
    "Iceland" : {"capital" : {"Reykjavik"}, "regions": ["europe"]},
    "India" : {"capital" : {"New Delhi"}, "regions": ["asia"]},
    "Indonesia" : {"capital" : {"Jakarta"}, "regions": ["asia", "southeast_asia"]},
    "Iran" : {"capital" : {"Tehran"}, "regions": ["asia", "middle_east"]},
    "Iraq" : {"capital" : {"Baghdad"}, "regions": ["asia", "middle_east"]},
    "Israel" : {"capital" : {"Jerusalem"}, "regions": ["asia", "middle_east"]},
    "Italy" : {"capital" : {"Rome"}, "regions": ["europe"]},
    "Jamaica" : {"capital" : {"Kingston"}, "regions": ["north_america", "americas", "caribbean"]},
    "Japan" : {"capital" : {"Tokyo"}, "regions": ["asia"]},
    "Jordan" : {"capital" : {"Amman"}, "regions": ["asia", "middle_east"]},
    "Kazakhstan" : {"capital" : {"Nur-Sultan", "Astana"}, "regions": ["asia", "europe"]},
    "Kenya" : {"capital" : {"Nairobi"}, "regions": ["africa"]},
    "Kiribati" : {"capital" : {"South Tarawa"}, "regions": ["oceania"]},
    "Kosovo" : {"capital" : {"Pristina"}, "regions": ["europe"]},
    "Kuwait" : {"capital" : {"Kuwait City"}, "regions": ["asia", "middle_east"]},
    "Kyrgyzstan" : {"capital" : {"Bishkek"}, "regions": ["asia"]},
    "Laos" : {"capital" : {"Vientiane"}, "regions": ["asia", "southeast_asia"]},
    "Latvia" : {"capital" : {"Riga"}, "regions": ["europe"]},
    "Lebanon" : {"capital" : {"Beirut"}, "regions": ["asia", "middle_east"]},
    "Lesotho" : {"capital" : {"Maseru"}, "regions": ["africa"]},
    "Liberia" : {"capital" : {"Monrovia"}, "regions": ["africa"]},
    "Libya" : {"capital" : {"Tripoli"}, "regions": ["africa"]},
    "Liechtenstein" : {"capital" : {"Vaduz"}, "regions": ["europe"]},
    "Lithuania" : {"capital" : {"Vilnius"}, "regions": ["europe"]},
    "Luxembourg" : {"capital" : {"Luxembourg City"}, "regions": ["europe"]},
    "Madagascar" : {"capital" : {"Antananarivo"}, "regions": ["africa"]},
    "Malawi" : {"capital" : {"Lilongwe"}, "regions": ["africa"]},
    "Malaysia" : {"capital" : {"Kuala Lumpur"}, "regions": ["asia", "southeast_asia"]},
    "Maldives" : {"capital" : {"Malé"}, "regions": ["asia"]},
    "Mali" : {"capital" : {"Bamako"}, "regions": ["africa"]},
    "Malta" : {"capital" : {"Valletta"}, "regions": ["europe"]},
    "Marshall Islands" : {"capital" : {"Majuro"}, "regions": ["oceania"]},
    "Mauritania" : {"capital" : {"Nouakchott"}, "regions": ["africa"]},
    "Mauritius" : {"capital" : {"Port Louis"}, "regions": ["africa"]},
    "Mexico" : {"capital" : {"Mexico City"}, "regions": ["north_america", "americas"]},
    "Micronesia" : {"capital" : {"Palikir"}, "regions": ["oceania"]},
    "Moldova" : {"capital" : {"Chisinau"}, "regions": ["europe"]},
    "Monaco" : {"capital" : {"Monaco"}, "regions": ["europe"]},
    "Mongolia" : {"capital" : {"Ulaanbaatar"}, "regions": ["asia"]},
    "Montenegro" : {"capital" : {"Podgorica"}, "regions": ["europe"]},
    "Morocco" : {"capital" : {"Rabat"}, "regions": ["africa"]},
    "Mozambique" : {"capital" : {"Maputo"}, "regions": ["africa"]},
    "Myanmar" : {"capital" : {("Naypyidaw","Nay Pyi Taw")}, "regions": ["asia", "southeast_asia"]},
    "Namibia" : {"capital" : {"Windhoek"}, "regions": ["africa"]},
    "Nauru" : {"capital" : {"Yaren"}, "regions": ["oceania"]},
    "Nepal" : {"capital" : {"Kathmandu"}, "regions": ["asia"]},
    "Netherlands" : {"capital" : {"Amsterdam"}, "regions": ["europe"]},
    "New Zealand" : {"capital" : {"Wellington"}, "regions": ["oceania"]},
    "Nicaragua" : {"capital" : {"Managua"}, "regions": ["north_america", "central_america", "americas"]},
    "Niger" : {"capital" : {"Niamey"}, "regions": ["africa"]},
    "Nigeria" : {"capital" : {"Abuja"}, "regions": ["africa"]},
    "Niue" : {"capital" : {"Alofi"}, "sovereign": False, "regions": ["oceania"]},
    "North Korea" : {"capital" : {"Pyongyang"}, "regions": ["asia"]},
    "Norway" : {"capital" : {"Oslo"}, "regions": ["europe"]},
    "Oman" : {"capital" : {"Muscat"}, "regions": ["asia", "middle_east"]},
    "Pakistan" : {"capital" : {"Islamabad"}, "regions": ["asia"]},
    "Palau" : {"capital" : {"Ngerulmud"}, "regions": ["oceania"]},
    "Palestine" : {"capital" : {"Jerusalem", "Ramallah"}, "regions": ["asia", "middle_east"]},
    "Panama" : {"capital" : {"Panama City"}, "regions": ["north_america", "central_america", "americas"]},
    "Papua New Guinea" : {"capital" : {"Port Moresby"}, "regions": ["oceania"]},
    "Paraguay" : {"capital" : {"Asuncion"}, "regions": ["south_america", "americas"]},
    "Peru" : {"capital" : {"Lima"}, "regions": ["south_america", "americas"]},
    "Philippines" : {"capital" : {"Manila"}, "regions": ["asia"]},
    "Poland" : {"capital" : {"Warsaw"}, "regions": ["europe"]},
    "Portugal" : {"capital" : {"Lisbon"}, "regions": ["europe"]},
    "Puerto Rico" : {"capital" : {"San Juan"}, "sovereign": False, "regions": ["north_america", "americas", "caribbean"]},
    "Qatar" : {"capital" : {"Doha"}, "regions": ["asia", "middle_east"]},
    "Republic of Ireland" : {"capital" : {"Dublin"}, "regions": ["europe"]},
    "Republic of North Macedonia" : {"capital" : {"Skopje"}, "regions": ["europe"]},
    "Republic of the Congo" : {"capital" : {"Brazzaville"}, "regions": ["africa"]},
    "Romania" : {"capital" : {"Bucharest"}, "regions": ["europe"]},
    "Russia" : {"capital" : {"Moscow"}, "regions": ["europe"]},
    "Rwanda" : {"capital" : {"Kigali"}, "regions": ["asia"]},
    "Saint Kitts and Nevis" : {"capital" : {"Basseterre"}, "regions": ["north_america", "americas", "caribbean"]},
    "Saint Lucia" : {"capital" : {"Castries"}, "regions": ["north_america", "americas", "caribbean"]},
    "Saint Vincent and the Grenadines" : {"capital" : {"Kingstown"}, "regions": ["north_america", "americas", "caribbean"]},
    "Samoa" : {"capital" : {"Apia"}, "regions": ["oceania"]},
    "San Marino" : {"capital" : {"San Marino"}, "regions": ["europe"]},
    "São Tomé and Príncipe" : {"capital" : {"São Tomé"}, "regions": ["africa"]},
    "Saudi Arabia" : {"capital" : {"Riyadh"}, "regions": ["asia", "middle_east"]},
    "Senegal" : {"capital" : {"Dakar"}, "regions": ["africa"]},
    "Serbia" : {"capital" : {"Belgrade"}, "regions": ["europe"]},
    "Seychelles" : {"capital" : {"Victoria"}, "regions": ["africa"]},
    "Sierra Leone" : {"capital" : {"Freetown"}, "regions": ["africa"]},
    "Singapore" : {"capital" : {"Singapore"}, "regions": ["asia", "southeast_asia"]},
    "Slovakia" : {"capital" : {"Bratislava"}, "regions": ["europe"]},
    "Slovenia" : {"capital" : {"Ljubljana"}, "regions": ["europe"]},
    "Solomon Islands" : {"capital" : {"Honiara"}, "regions": ["oceania"]},
    "Somalia" : {"capital" : {"Mogadishu"}, "regions": ["africa"]},
    "South Africa" : {"capital" : {"Pretoria", "Cape Town", "Bloemfontein"}, "regions": ["africa"]},
    "South Korea" : {"capital" : {"Seoul"}, "regions": ["asia"]},
    "South Sudan" : {"capital" : {"Juba"}, "regions": ["africa"]},
    "Spain" : {"capital" : {"Madrid"}, "regions": ["europe"]},
    "Sri Lanka" : {"capital" : {"Sri Jayawardenapura Kotte", "Colombo"}, "regions": ["asia"]},
    "Sudan" : {"capital" : {"Khartoum"}, "regions": ["africa"]},
    "Suriname" : {"capital" : {"Paramaribo"}, "regions": ["south_america", "americas"]},
    "Sweden" : {"capital" : {"Stockholm"}, "regions": ["europe"]},
    "Switzerland" : {"capital" : {"Bern"}, "regions": ["europe"]},
    "Syria" : {"capital" : {"Damascus"}, "regions": ["asia", "middle_east"]},
    "Taiwan" : {"capital" : {"Taipei"}, "regions": ["asia"]},
    "Tajikistan" : {"capital" : {"Dushanbe"}, "regions": ["asia"]},
    "Tanzania" : {"capital" : {"Dodoma"}, "regions": ["africa"]},
    "Thailand" : {"capital" : {"Bangkok"}, "regions": ["asia", "southeast_asia"]},
    "Togo" : {"capital" : {"Lome"}, "regions": ["africa"]},
    "Tonga" : {"capital" : {"Nuku'alofa"}, "regions": ["oceania"]},
    "Trinidad and Tobago" : {"capital" : {"Port of Spain"}, "regions": ["north_america", "americas", "caribbean"]},
    "Tunisia" : {"capital" : {"Tunis"}, "regions": ["africa"]},
    "Turkey" : {"capital" : {"Ankara"}, "regions": ["asia", "europe"]},
    "Turkmenistan" : {"capital" : {"Ashgabat"}, "regions": ["asia"]},
    "Turks and Caicos" : {"capital" : {"Cockburn Town"}, "sovereign": False, "regions": ["north_america", "americas", "caribbean"]},
    "Tuvalu" : {"capital" : {"Funafuti"}, "regions": ["oceania"]},
    "Uganda" : {"capital" : {"Kampala"}, "regions": ["africa"]},
    "Ukraine" : {"capital" : {("Kyiv", "Kiev")}, "regions": ["europe"]},
    "United Arab Emirates" : {"capital" : {"Abu Dhabi"}, "regions": ["asia", "middle_east"]},
    "United Kingdom" : {"capital" : {"London"}, "regions": ["europe"]},
    "United States of America" : {"capital" : {("Washington, D.C.", "D.C.", "District of Colombia")}, "regions": ["north_america", "americas"]},
    "Uruguay" : {"capital" : {"Montevideo"}, "regions": ["south_america", "americas"]},
    "Uzbekistan" : {"capital" : {"Tashkent"}, "regions": ["asia"]},
    "Vanuatu" : {"capital" : {"Port Vila"}, "regions": ["oceania"]},
    "Vatican City" : {"capital" : {"Vatican City"}, "regions": ["europe"]},
    "Venezuela" : {"capital" : {"Caracas"}, "regions": ["south_america", "americas"]},
    "Vietnam" : {"capital" : {"Hanoi"}, "regions": ["asia", "southeast_asia"]},
    "Yemen" : {"capital" : {"Sana'a"}, "regions": ["asia", "middle_east"]},
    "Zambia" : {"capital" : {"Lusaka"}, "regions": ["africa"]},
    "Zimbabwe" : {"capital" : {"Harare"}, "regions": ["africa"]}
}
